### ISSUE TITLE
request for `JLNamedTuple <: JLExpr`

### ISSUE THREAD

**Issue by JeffreySarnoff** [Roger-luo/Expronicon.jl#10]
I am as yet too unfamiliar with this sort of metaprogramming to offer a PR.

Wherever I notice special treatment of Structs and that flexibility has not extended to NamedTuples or where Structs benefit from dedicated dispatch specialization not yet supported for NamedTuples, there is an opportunity to ask for playing-field leveling. Usually this is not difficult for the person who has written the code in support of Structs, as there are similarities in structural design.

**Comment by Roger-luo** [comment]
the `NamedTuple` syntax has no difference with a `Tuple` in Julia `Expr` object: https://docs.julialang.org/en/v1/devdocs/ast/#Bracketed-forms

> Usually this is not difficult for the person who has written the code in support of Structs, as there are similarities in structural design.

It is not difficult but it doesn't make sense to me at the moment, thus I don't know why would one use a `JLNamedTuple` and what convenience it can provide.
what is the actual use case you have in mind?

**Comment by JeffreySarnoff** [comment]
I am comfortable deferring to your better knowledge of how best to apply your package.
I had no applied use at hand. Were it extant, I would have spent time experimenting and comparing/contrasting JLStruct as a way to simplify my own learning curve.

It sounds like that would have lead me to conclude "The goal of syntax types is not to define
a struct for every Julia syntax, it is a specific data structure for manipulation/analysis/code generation for some complicated Julia syntax." I had been examining possible shortcuts and
trying ways to obtain more accurate `eltype(vector_of_types)` that arise in some expression manipulation and reconstructive microsurgery that I would use in NamedTupleTools.jl.

The next time I replicate that example, if I still do not see the solution approach -- I will ask.
_Thank you for being so responsive._

**Comment by Roger-luo** [comment]
You can't get any type information at `Expr` level - the typeinf has not occur yet. To obtain type information, perhaps look at generated functions or just use functions.

**Comment by Roger-luo** [comment]
But if you have a more concrete example of what you want to do using meta programming (e.g the code of original expression, and the code you want to generate) feel free to post them in the issues or ask in slack channels
