### ISSUE TITLE
[Feature Request] Auto generate `hash` and `(==)` for ADT.

### ISSUE THREAD

**Issue by weinbe58** [Roger-luo/Expronicon.jl#49]
I think this would greatly decrease the amount of boiler plate code that is needed to start using an ADT. 

As long as the  semantics tree is inferable from the ADT it should be possible to auto-generate this functionality. I guess the question is how to export those functions but perhaps you can put the implementations in the ADT namespace like the variant types. Then later all one would have to do is wrap them with `Base.hash(x::MyADT, h::UInt) = MyADT.hash(x, h)` and similar for `==`

What do you think?

**Comment by Roger-luo** [comment]
yes, that's something I want to have actually, but haven't spent much time thinking about it, it's basically `AutoHashEqual` package but for ADTs. We should be able to just overload `hash` directly with an option in the macro (ideally it should be a derivable trait, but we don't have any builtin traits in Julia...)

**Comment by weinbe58** [comment]
Let's discuss this week or early next week, maybe I can help out

**Comment by Roger-luo** [comment]
```julia
@adt MyADT begin
   @hash_equal struct CanBeHashed
      a::Int
      b::Int
   end

   struct NotDirectHashable
      h::Ref{Int}
   end
end
```

for all hashable

```julia
@hash_equal MyADT
```

**Comment by weinbe58** [comment]
```julia
@adt First begin
    ...
end

@adt Second begin
    variant_type(::First)
    ...
end
```

**Comment by Roger-luo** [comment]
@hash_equal First
@hash_equal Second

```julia
hash_equal_trait(::Type{T}) where {T} = applicable(hash, T) && applicable(==, T)
hash_equal_trait(::Type{First}) = true
hash_equal_trait(::Type{Second}) = true
```

**Comment by Roger-luo** [comment]
this is now supported in Moshi as the `@derive` macro
